apiVersion: harness.io/v1
kind: Component
type: service
identifier: harnesscoderepo
name: harness code repo
owner: Harness_Account_All_Users
spec:
  lifecycle: experimental
  providesApis:
  - idp-Service-api
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
    gitlab.com/project-id: '43877214'
    jira/project-key: IDP
    jenkins.io/github-folder: CDS-68313
    firehydrant.com/service-name: python-pipeline-samples
    backstage.io/kubernetes-label-selector: app=idp-ui
    backstage.io/kubernetes-namespace: 63feee14cbf66e3c798c4bdc
    github.com/project-slug: vigneswara-propelo/python-pipeline-samples
    harness.io/pipelines: |
      Build: https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/all/orgs/default/projects/idptestharness/pipelines/cipipelinetest/executions/EtQuSATdQH2CBagwyNwsVw/pipeline?storeType=INLINE
    harness.io/services: |
      cd: https://stress.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/cd/orgs/default/projects/idptestharness/services/testservice
    pagerduty.com/service-id: PNISOWY
    backstage.io/source-location: url:https://qa.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/module/code/repos/agniva_test_repository/files/develop/~/
  harnessData:
    name: Microservice.AppD
  customField: custom1
  tags:
  - java
  - food-ordering
