apiVersion: harness.io/v1
kind: Component
type: component
identifier: test_ccp_data
name: Test CCP Data
owner: user:account/rbac1@harness.io
spec:
  lifecycle: experimental
  ownedBy:
  - user:account/rbac1@harness.io
metadata:
  tags:
  - java
  - python
  - test
