apiVersion: harness.io/v1
kind: Component
type: component
identifier: test_remote_catalog8
name: Test Remote Catalog8
owner: user:account/admin@harness.io
spec:
  lifecycle: experimental
metadata:
  tags:
